### ISSUE TITLE
Add support for versatile_block_paras to section_start_rules.js

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_validator#104]

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted PR for review: https://github.com/macmillanpublishers/bookmaker_validator/pull/105

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

Submitted new PR for review with updates to point to new in-file and take an array of styles instead of classes:  https://github.com/macmillanpublishers/bookmaker_validator/pull/109

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

This has been approved and merged into the sectionstartstaging branch for bookmaker_validator repo
