### ISSUE TITLE
Coresource auto-upload should be skipped if epubcheck failed

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_validator#110]

**Comment by mattretzer** [comment]
This would actually be an addition to this script:
https://github.com/macmillanpublishers/bookmaker_connectors/blob/master/epub_to_coresourceSend.rb 
Just skipping copy-files to corseource_dir if the epucheck_error file existed would do the trick. We're already getting an epubcheck error alert through validator_posts.

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

Submitted for review, https://github.com/macmillanpublishers/bookmaker_connectors/pull/1

**Comment by MacmillanWorkflows** [comment]
➤ 9491251705208 commented:

approved, merged deployed, re-tested, done!
