### ISSUE TITLE
Patrick W. is still getting emails for QA'ing epubs, has left the company

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_validator#115]
Checking with his team to see if they want to change the person receiving the emails.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

submitted PR for review : https://github.com/macmillanpublishers/bookmaker_validator/pull/116

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:

merged & deployed
