### ISSUE TITLE
Dedication should *not* have header

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_validator#49]
For dedication paragraphs, no header should be inserted.

Sorry Erica :(

**Comment by nelliemckesson** [comment]
@ericawarren Argh SO while the dedication should not have a header, it *should* be preceded by a pagebreak paragraph. Sorry again :/ Didn't realize that was required.

**Comment by ericawarren** [comment]
@nelliemckesson there should be a pagebreak paragraph added before every heading section (though not a page break character, just a paragraph return styled as "Page Break"). Did that not happen on a specific manuscript?

**Comment by nelliemckesson** [comment]
WELL the thing is, we took out the heading for dedications. Is there a way to add a pagebreak paragraph before the first instance of Dedication (ded).

**Comment by ericawarren** [comment]
oh, yes, that will happen. The logic for sections/headings/etc:

* For each "Page Break"-styled paragraph:
  * Is the following paragraph an acceptable heading? (list of acceptable headings is currently hard-coded, but I am going to move that to a JSON file)
  * If not, get the first word of the style of that paragraph, and add a heading paragraph above it with the text and style from [this file](https://github.com/macmillanpublishers/vba_utilities/blob/master/genUtils/sections.json).
  * Remove Page Break paragraphs (so we can add later consistently)
* Loop through each paragraph to identify FIRST heading style in a block (i.e., three heading paragraphs in a row -- like for a copyright page -- aren't counted as separate headings)
* Create array of ranges based on the paragraph indexes created above, then loop through these ranges to validate various heading requirements and add a page break paragraph at the end.

So all we need to do is add "Dedication (ded)" to the list of acceptable headings, and we're good to go. I was going to open a pull request today with a bunch of fixes, but if this one is urgent I can just submit that one thing now in like 5 minutes.

**Comment by nelliemckesson** [comment]
Great! Yeah, it's semi-urgent, since most books seem to have a dedication,
and as things stand now, the dedication is getting lumped in with the
copyright page (which is bad).
