### ISSUE TITLE
Switch Core Source Upload to sftp

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_validator#59]
From the Dropbox CoureSource Send folder, now that we can sftp from the server(s).
Checking / some level of QA should def. be considered part of this too.

**Comment by nelliemckesson** [comment]
I went ahead and switched the send_to_coresource folders to load directly to CoreSource ftp. When you add this functioanlity to egalleymaker, you should either just transfer the file to the send_to_coresource folder and let those scripts take care of it, or use the same script inside your own process (utilities/coresource_connector).
