### ISSUE TITLE
File rename interferes with filename error mailer

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_validator#61]
When a submitted .doc file is renamed to remove special characters, the submitter name from Dropbox seems to be lost, which causes errors (e.g., missing ISBN error) to go to the workflows email address.

**Comment by nelliemckesson** [comment]
Also appears that the submitter is not getting the "Success" email that notifies them when a file is being processed by egalleymaker. Looks like submitter name is just getting stored as "workflows".

**Comment by mattretzer** [comment]
resolved by PR #63
