### ISSUE TITLE
Dropbox API lookup fails in validator

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_validator#66]
After last update, submitter lookup fails with any file, returns error file to user with "The submitted document was not a .doc or .docx: "GUnit_DupeMS.docx"

Logs from error here: 
[GUnit_DupeMS_log.txt](https://github.com/macmillanpublishers/bookmaker_validator/files/562856/GUnit_DupeMS_log.txt)

But it also failed on staging with the validator test file. I'll email the PM to let them know the MS is not styled, and @nelliemckesson is rolling back the code on the servers.

**Comment by mattretzer** [comment]
Resolved with PR #67
