### ISSUE TITLE
Validator added 2 section breaks mysteriously

### ISSUE THREAD

**Issue by ericawarren** [macmillanpublishers/bookmaker_validator#68]
See folder for this issue in Dropbox/wacky_files.

Original doc had no section breaks. Final validator output had Next Page section breaks added just before chapters Nine and Nineteen, which subsequently caused epubcheck errors.

**Comment by nelliemckesson** [comment]
More info in https://github.com/macmillanpublishers/bookmaker_validator/issues/69
