### ISSUE TITLE
Custom Dialog style restyled as Dedication

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_validator#83]
Custom dialog style "Text - Dialogue 2 (dia2)" was restyled as Dedication in Randall_UNSHACKLINGAMERICA, 9781250111838. Screenshots from original MS and validated MS below. 

Original:
![screenshot 2017-01-09 11 12 02](https://cloud.githubusercontent.com/assets/812739/21773364/b3462e4e-d65c-11e6-9935-519998cfe6cd.png)

Validated:
![screenshot 2017-01-09 11 11 50](https://cloud.githubusercontent.com/assets/812739/21773367/b7cf67d2-d65c-11e6-9cc3-250cd6f3cbd6.png)

**Comment by ericawarren** [comment]
The custom style has the correct naming convention, but it was "based on" the Dedication style for some reason. The validator macro converts any custom styles to the style they were based on, hence they were converted to dedication. Whoever created the custom style should have started with the dialog style, not dedication, when creating the custom style.
![screenshot_2017-01-11_17_54_36](https://cloud.githubusercontent.com/assets/7770929/21874058/78589624-d827-11e6-87aa-df80993e54e6.png)

**Comment by nelliemckesson** [comment]
I understand why we set this up this way, but it does leave room for problems like this. My new CSS handling plan would actually correct for this on the bookmaker side of things, but I'm not sure when I'll have that done. I suppose we'll have to let this sit until then, though.

**Comment by MacmillanWorkflows** [comment]
➤ erica.warren commented:
Also as part of the revised style names/handling on the Word-template side, we could bump up https://app.asana.com/0/207116201162632/192736275403838 so we have control of the process.
