### ISSUE TITLE
When using 'Workflows' as PM, email notification needs 'Alert' in the subject

### ISSUE THREAD

**Issue by mattretzer** [macmillanpublishers/bookmaker_validator#87]
We had a case today where there was no PM associated with a title in Biblio, and the submitter was not in our staff list; so "Workflows" with our email address became the default PM.
https://www.dropbox.com/s/1b7mv1gfmsi0ed7/9781250104052_LucaCEfromauthor_log.txt?dl=0

That part is good; but the email subject then needs to reflect an Alert or Error condition so we know that we need to pay attention to the notification

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Requested review of PR for this issue: https://github.com/macmillanpublishers/bookmaker_validator/pull/88

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
merged, tested again, ok
