### ISSUE TITLE
[ss] Convert to basic HTML

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_validator#90]
Once all other macros have run, convert the .docx to basic HTML via htmlmaker_js.

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
Submitted PR for Nellie's review: https://github.com/macmillanpublishers/bookmaker_validator/pull/95

**Comment by MacmillanWorkflows** [comment]
➤ Matthew Retzer commented:
This was deployed! : https://github.com/macmillanpublishers/bookmaker_validator/pull/95
